server:
  port: 8049
  servlet:
    context-path: /comment

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://121.40.33.146:3306/news?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
      username: root
      password: 123456

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.yjls.entity

dubbo:
  application:
    name: news-comment
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    port: -1 # random port
  consumer:
    timeout: 6000
  provider:
    timeout: 6000

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check

